# Generated by Django 3.2.6 on 2022-01-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Risk_free_rate', models.CharField(max_length=10, null=True)),
                ('Market_Premium', models.CharField(max_length=10, null=True)),
                ('Beta', models.CharField(max_length=10, null=True)),
                ('Effective_tax_Rate', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
